// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/rpc/longrunning/operation.proto

package org.mojo-lang.mojo.rpc.longrunning;

public final class OperationProto {
  private OperationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_rpc_longrunning_Operation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_rpc_longrunning_Operation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$mojo/rpc/longrunning/operation.proto\022\024" +
      "mojo.rpc.longrunning\032\023mojo/core/any.prot" +
      "o\032\025mojo/core/error.proto\"\214\001\n\tOperation\022\014" +
      "\n\004name\030\001 \001(\t\022 \n\010metadata\030\002 \001(\0132\016.mojo.co" +
      "re.Any\022\014\n\004done\030\003 \001(\010\022\037\n\005error\030\004 \001(\0132\020.mo" +
      "jo.core.Error\022 \n\010response\030\005 \001(\0132\016.mojo.c" +
      "ore.AnyBx\n\"org.mojo-lang.mojo.rpc.longru" +
      "nningB\016OperationProtoP\001Z@github.com/mojo" +
      "-lang/rpc/go/pkg/mojo/rpc/longrunning;lo" +
      "ngrunningb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.AnyProto.getDescriptor(),
          org.mojolang.mojo.core.ErrorProto.getDescriptor(),
        });
    internal_static_mojo_rpc_longrunning_Operation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_rpc_longrunning_Operation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_rpc_longrunning_Operation_descriptor,
        new java.lang.String[] { "Name", "Metadata", "Done", "Error", "Response", });
    org.mojolang.mojo.core.AnyProto.getDescriptor();
    org.mojolang.mojo.core.ErrorProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
