// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/rpc/longrunning/operation.proto

package org.mojo-lang.mojo.rpc.longrunning;

public interface OperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.rpc.longrunning.Operation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [(.mojo.key) = ""];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [(.mojo.key) = ""];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string parent_name = 10 [(.mojo.db_index) = ""];</code>
   * @return The parentName.
   */
  java.lang.String getParentName();
  /**
   * <code>string parent_name = 10 [(.mojo.db_index) = ""];</code>
   * @return The bytes for parentName.
   */
  com.google.protobuf.ByteString
      getParentNameBytes();

  /**
   * <code>.mojo.core.Any metadata = 2;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.mojo.core.Any metadata = 2;</code>
   * @return The metadata.
   */
  org.mojolang.mojo.core.Any getMetadata();
  /**
   * <code>.mojo.core.Any metadata = 2;</code>
   */
  org.mojolang.mojo.core.AnyOrBuilder getMetadataOrBuilder();

  /**
   * <code>bool done = 3;</code>
   * @return The done.
   */
  boolean getDone();

  /**
   * <code>.mojo.core.Error error = 4;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>.mojo.core.Error error = 4;</code>
   * @return The error.
   */
  org.mojolang.mojo.core.Error getError();
  /**
   * <code>.mojo.core.Error error = 4;</code>
   */
  org.mojolang.mojo.core.ErrorOrBuilder getErrorOrBuilder();

  /**
   * <code>.mojo.core.Any response = 5;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.mojo.core.Any response = 5;</code>
   * @return The response.
   */
  org.mojolang.mojo.core.Any getResponse();
  /**
   * <code>.mojo.core.Any response = 5;</code>
   */
  org.mojolang.mojo.core.AnyOrBuilder getResponseOrBuilder();
}
