// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/rpc/longrunning/operation.proto

package org.mojo-lang.mojo.rpc.longrunning;

/**
 * Protobuf type {@code mojo.rpc.longrunning.Operation}
 */
public final class Operation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.rpc.longrunning.Operation)
    OperationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Operation.newBuilder() to construct.
  private Operation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Operation() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Operation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Operation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            org.mojolang.mojo.core.Any.Builder subBuilder = null;
            if (metadata_ != null) {
              subBuilder = metadata_.toBuilder();
            }
            metadata_ = input.readMessage(org.mojolang.mojo.core.Any.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(metadata_);
              metadata_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            done_ = input.readBool();
            break;
          }
          case 34: {
            org.mojolang.mojo.core.Error.Builder subBuilder = null;
            if (resultCase_ == 4) {
              subBuilder = ((org.mojolang.mojo.core.Error) result_).toBuilder();
            }
            result_ =
                input.readMessage(org.mojolang.mojo.core.Error.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.mojolang.mojo.core.Error) result_);
              result_ = subBuilder.buildPartial();
            }
            resultCase_ = 4;
            break;
          }
          case 42: {
            org.mojolang.mojo.core.Any.Builder subBuilder = null;
            if (resultCase_ == 5) {
              subBuilder = ((org.mojolang.mojo.core.Any) result_).toBuilder();
            }
            result_ =
                input.readMessage(org.mojolang.mojo.core.Any.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.mojolang.mojo.core.Any) result_);
              result_ = subBuilder.buildPartial();
            }
            resultCase_ = 5;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojo-lang.mojo.rpc.longrunning.OperationProto.internal_static_mojo_rpc_longrunning_Operation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojo-lang.mojo.rpc.longrunning.OperationProto.internal_static_mojo_rpc_longrunning_Operation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojo-lang.mojo.rpc.longrunning.Operation.class, org.mojo-lang.mojo.rpc.longrunning.Operation.Builder.class);
  }

  private int resultCase_ = 0;
  private java.lang.Object result_;
  public enum ResultCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    MOJO_CORE_ERROR(4),
    MOJO_CORE_ANY(5),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 4: return MOJO_CORE_ERROR;
        case 5: return MOJO_CORE_ANY;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATA_FIELD_NUMBER = 2;
  private org.mojolang.mojo.core.Any metadata_;
  /**
   * <code>.mojo.core.Any metadata = 2;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return metadata_ != null;
  }
  /**
   * <code>.mojo.core.Any metadata = 2;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public org.mojolang.mojo.core.Any getMetadata() {
    return metadata_ == null ? org.mojolang.mojo.core.Any.getDefaultInstance() : metadata_;
  }
  /**
   * <code>.mojo.core.Any metadata = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.AnyOrBuilder getMetadataOrBuilder() {
    return getMetadata();
  }

  public static final int DONE_FIELD_NUMBER = 3;
  private boolean done_;
  /**
   * <code>bool done = 3;</code>
   * @return The done.
   */
  @java.lang.Override
  public boolean getDone() {
    return done_;
  }

  public static final int MOJO_CORE_ERROR_FIELD_NUMBER = 4;
  /**
   * <code>.mojo.core.Error mojo_core_error = 4;</code>
   * @return Whether the mojoCoreError field is set.
   */
  @java.lang.Override
  public boolean hasMojoCoreError() {
    return resultCase_ == 4;
  }
  /**
   * <code>.mojo.core.Error mojo_core_error = 4;</code>
   * @return The mojoCoreError.
   */
  @java.lang.Override
  public org.mojolang.mojo.core.Error getMojoCoreError() {
    if (resultCase_ == 4) {
       return (org.mojolang.mojo.core.Error) result_;
    }
    return org.mojolang.mojo.core.Error.getDefaultInstance();
  }
  /**
   * <code>.mojo.core.Error mojo_core_error = 4;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.ErrorOrBuilder getMojoCoreErrorOrBuilder() {
    if (resultCase_ == 4) {
       return (org.mojolang.mojo.core.Error) result_;
    }
    return org.mojolang.mojo.core.Error.getDefaultInstance();
  }

  public static final int MOJO_CORE_ANY_FIELD_NUMBER = 5;
  /**
   * <code>.mojo.core.Any mojo_core_any = 5;</code>
   * @return Whether the mojoCoreAny field is set.
   */
  @java.lang.Override
  public boolean hasMojoCoreAny() {
    return resultCase_ == 5;
  }
  /**
   * <code>.mojo.core.Any mojo_core_any = 5;</code>
   * @return The mojoCoreAny.
   */
  @java.lang.Override
  public org.mojolang.mojo.core.Any getMojoCoreAny() {
    if (resultCase_ == 5) {
       return (org.mojolang.mojo.core.Any) result_;
    }
    return org.mojolang.mojo.core.Any.getDefaultInstance();
  }
  /**
   * <code>.mojo.core.Any mojo_core_any = 5;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.AnyOrBuilder getMojoCoreAnyOrBuilder() {
    if (resultCase_ == 5) {
       return (org.mojolang.mojo.core.Any) result_;
    }
    return org.mojolang.mojo.core.Any.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (metadata_ != null) {
      output.writeMessage(2, getMetadata());
    }
    if (done_ != false) {
      output.writeBool(3, done_);
    }
    if (resultCase_ == 4) {
      output.writeMessage(4, (org.mojolang.mojo.core.Error) result_);
    }
    if (resultCase_ == 5) {
      output.writeMessage(5, (org.mojolang.mojo.core.Any) result_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (metadata_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMetadata());
    }
    if (done_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, done_);
    }
    if (resultCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (org.mojolang.mojo.core.Error) result_);
    }
    if (resultCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (org.mojolang.mojo.core.Any) result_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojo-lang.mojo.rpc.longrunning.Operation)) {
      return super.equals(obj);
    }
    org.mojo-lang.mojo.rpc.longrunning.Operation other = (org.mojo-lang.mojo.rpc.longrunning.Operation) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (getDone()
        != other.getDone()) return false;
    if (!getResultCase().equals(other.getResultCase())) return false;
    switch (resultCase_) {
      case 4:
        if (!getMojoCoreError()
            .equals(other.getMojoCoreError())) return false;
        break;
      case 5:
        if (!getMojoCoreAny()
            .equals(other.getMojoCoreAny())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (37 * hash) + DONE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDone());
    switch (resultCase_) {
      case 4:
        hash = (37 * hash) + MOJO_CORE_ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getMojoCoreError().hashCode();
        break;
      case 5:
        hash = (37 * hash) + MOJO_CORE_ANY_FIELD_NUMBER;
        hash = (53 * hash) + getMojoCoreAny().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojo-lang.mojo.rpc.longrunning.Operation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojo-lang.mojo.rpc.longrunning.Operation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojo-lang.mojo.rpc.longrunning.Operation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojo-lang.mojo.rpc.longrunning.Operation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojo-lang.mojo.rpc.longrunning.Operation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojo-lang.mojo.rpc.longrunning.Operation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojo-lang.mojo.rpc.longrunning.Operation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojo-lang.mojo.rpc.longrunning.Operation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojo-lang.mojo.rpc.longrunning.Operation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojo-lang.mojo.rpc.longrunning.Operation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojo-lang.mojo.rpc.longrunning.Operation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojo-lang.mojo.rpc.longrunning.Operation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojo-lang.mojo.rpc.longrunning.Operation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.rpc.longrunning.Operation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.rpc.longrunning.Operation)
      org.mojo-lang.mojo.rpc.longrunning.OperationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojo-lang.mojo.rpc.longrunning.OperationProto.internal_static_mojo_rpc_longrunning_Operation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojo-lang.mojo.rpc.longrunning.OperationProto.internal_static_mojo_rpc_longrunning_Operation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojo-lang.mojo.rpc.longrunning.Operation.class, org.mojo-lang.mojo.rpc.longrunning.Operation.Builder.class);
    }

    // Construct using org.mojo-lang.mojo.rpc.longrunning.Operation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      if (metadataBuilder_ == null) {
        metadata_ = null;
      } else {
        metadata_ = null;
        metadataBuilder_ = null;
      }
      done_ = false;

      resultCase_ = 0;
      result_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojo-lang.mojo.rpc.longrunning.OperationProto.internal_static_mojo_rpc_longrunning_Operation_descriptor;
    }

    @java.lang.Override
    public org.mojo-lang.mojo.rpc.longrunning.Operation getDefaultInstanceForType() {
      return org.mojo-lang.mojo.rpc.longrunning.Operation.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojo-lang.mojo.rpc.longrunning.Operation build() {
      org.mojo-lang.mojo.rpc.longrunning.Operation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojo-lang.mojo.rpc.longrunning.Operation buildPartial() {
      org.mojo-lang.mojo.rpc.longrunning.Operation result = new org.mojo-lang.mojo.rpc.longrunning.Operation(this);
      result.name_ = name_;
      if (metadataBuilder_ == null) {
        result.metadata_ = metadata_;
      } else {
        result.metadata_ = metadataBuilder_.build();
      }
      result.done_ = done_;
      if (resultCase_ == 4) {
        if (mojoCoreErrorBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = mojoCoreErrorBuilder_.build();
        }
      }
      if (resultCase_ == 5) {
        if (mojoCoreAnyBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = mojoCoreAnyBuilder_.build();
        }
      }
      result.resultCase_ = resultCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojo-lang.mojo.rpc.longrunning.Operation) {
        return mergeFrom((org.mojo-lang.mojo.rpc.longrunning.Operation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojo-lang.mojo.rpc.longrunning.Operation other) {
      if (other == org.mojo-lang.mojo.rpc.longrunning.Operation.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      if (other.getDone() != false) {
        setDone(other.getDone());
      }
      switch (other.getResultCase()) {
        case MOJO_CORE_ERROR: {
          mergeMojoCoreError(other.getMojoCoreError());
          break;
        }
        case MOJO_CORE_ANY: {
          mergeMojoCoreAny(other.getMojoCoreAny());
          break;
        }
        case RESULT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojo-lang.mojo.rpc.longrunning.Operation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojo-lang.mojo.rpc.longrunning.Operation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int resultCase_ = 0;
    private java.lang.Object result_;
    public ResultCase
        getResultCase() {
      return ResultCase.forNumber(
          resultCase_);
    }

    public Builder clearResult() {
      resultCase_ = 0;
      result_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.core.Any metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Any, org.mojolang.mojo.core.Any.Builder, org.mojolang.mojo.core.AnyOrBuilder> metadataBuilder_;
    /**
     * <code>.mojo.core.Any metadata = 2;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return metadataBuilder_ != null || metadata_ != null;
    }
    /**
     * <code>.mojo.core.Any metadata = 2;</code>
     * @return The metadata.
     */
    public org.mojolang.mojo.core.Any getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? org.mojolang.mojo.core.Any.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.core.Any metadata = 2;</code>
     */
    public Builder setMetadata(org.mojolang.mojo.core.Any value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
        onChanged();
      } else {
        metadataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.core.Any metadata = 2;</code>
     */
    public Builder setMetadata(
        org.mojolang.mojo.core.Any.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
        onChanged();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.core.Any metadata = 2;</code>
     */
    public Builder mergeMetadata(org.mojolang.mojo.core.Any value) {
      if (metadataBuilder_ == null) {
        if (metadata_ != null) {
          metadata_ =
            org.mojolang.mojo.core.Any.newBuilder(metadata_).mergeFrom(value).buildPartial();
        } else {
          metadata_ = value;
        }
        onChanged();
      } else {
        metadataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.core.Any metadata = 2;</code>
     */
    public Builder clearMetadata() {
      if (metadataBuilder_ == null) {
        metadata_ = null;
        onChanged();
      } else {
        metadata_ = null;
        metadataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.core.Any metadata = 2;</code>
     */
    public org.mojolang.mojo.core.Any.Builder getMetadataBuilder() {
      
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.core.Any metadata = 2;</code>
     */
    public org.mojolang.mojo.core.AnyOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            org.mojolang.mojo.core.Any.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <code>.mojo.core.Any metadata = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Any, org.mojolang.mojo.core.Any.Builder, org.mojolang.mojo.core.AnyOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.core.Any, org.mojolang.mojo.core.Any.Builder, org.mojolang.mojo.core.AnyOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private boolean done_ ;
    /**
     * <code>bool done = 3;</code>
     * @return The done.
     */
    @java.lang.Override
    public boolean getDone() {
      return done_;
    }
    /**
     * <code>bool done = 3;</code>
     * @param value The done to set.
     * @return This builder for chaining.
     */
    public Builder setDone(boolean value) {
      
      done_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool done = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDone() {
      
      done_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Error, org.mojolang.mojo.core.Error.Builder, org.mojolang.mojo.core.ErrorOrBuilder> mojoCoreErrorBuilder_;
    /**
     * <code>.mojo.core.Error mojo_core_error = 4;</code>
     * @return Whether the mojoCoreError field is set.
     */
    @java.lang.Override
    public boolean hasMojoCoreError() {
      return resultCase_ == 4;
    }
    /**
     * <code>.mojo.core.Error mojo_core_error = 4;</code>
     * @return The mojoCoreError.
     */
    @java.lang.Override
    public org.mojolang.mojo.core.Error getMojoCoreError() {
      if (mojoCoreErrorBuilder_ == null) {
        if (resultCase_ == 4) {
          return (org.mojolang.mojo.core.Error) result_;
        }
        return org.mojolang.mojo.core.Error.getDefaultInstance();
      } else {
        if (resultCase_ == 4) {
          return mojoCoreErrorBuilder_.getMessage();
        }
        return org.mojolang.mojo.core.Error.getDefaultInstance();
      }
    }
    /**
     * <code>.mojo.core.Error mojo_core_error = 4;</code>
     */
    public Builder setMojoCoreError(org.mojolang.mojo.core.Error value) {
      if (mojoCoreErrorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        mojoCoreErrorBuilder_.setMessage(value);
      }
      resultCase_ = 4;
      return this;
    }
    /**
     * <code>.mojo.core.Error mojo_core_error = 4;</code>
     */
    public Builder setMojoCoreError(
        org.mojolang.mojo.core.Error.Builder builderForValue) {
      if (mojoCoreErrorBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        mojoCoreErrorBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 4;
      return this;
    }
    /**
     * <code>.mojo.core.Error mojo_core_error = 4;</code>
     */
    public Builder mergeMojoCoreError(org.mojolang.mojo.core.Error value) {
      if (mojoCoreErrorBuilder_ == null) {
        if (resultCase_ == 4 &&
            result_ != org.mojolang.mojo.core.Error.getDefaultInstance()) {
          result_ = org.mojolang.mojo.core.Error.newBuilder((org.mojolang.mojo.core.Error) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 4) {
          mojoCoreErrorBuilder_.mergeFrom(value);
        }
        mojoCoreErrorBuilder_.setMessage(value);
      }
      resultCase_ = 4;
      return this;
    }
    /**
     * <code>.mojo.core.Error mojo_core_error = 4;</code>
     */
    public Builder clearMojoCoreError() {
      if (mojoCoreErrorBuilder_ == null) {
        if (resultCase_ == 4) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 4) {
          resultCase_ = 0;
          result_ = null;
        }
        mojoCoreErrorBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.mojo.core.Error mojo_core_error = 4;</code>
     */
    public org.mojolang.mojo.core.Error.Builder getMojoCoreErrorBuilder() {
      return getMojoCoreErrorFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.core.Error mojo_core_error = 4;</code>
     */
    @java.lang.Override
    public org.mojolang.mojo.core.ErrorOrBuilder getMojoCoreErrorOrBuilder() {
      if ((resultCase_ == 4) && (mojoCoreErrorBuilder_ != null)) {
        return mojoCoreErrorBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 4) {
          return (org.mojolang.mojo.core.Error) result_;
        }
        return org.mojolang.mojo.core.Error.getDefaultInstance();
      }
    }
    /**
     * <code>.mojo.core.Error mojo_core_error = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Error, org.mojolang.mojo.core.Error.Builder, org.mojolang.mojo.core.ErrorOrBuilder> 
        getMojoCoreErrorFieldBuilder() {
      if (mojoCoreErrorBuilder_ == null) {
        if (!(resultCase_ == 4)) {
          result_ = org.mojolang.mojo.core.Error.getDefaultInstance();
        }
        mojoCoreErrorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.core.Error, org.mojolang.mojo.core.Error.Builder, org.mojolang.mojo.core.ErrorOrBuilder>(
                (org.mojolang.mojo.core.Error) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 4;
      onChanged();;
      return mojoCoreErrorBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Any, org.mojolang.mojo.core.Any.Builder, org.mojolang.mojo.core.AnyOrBuilder> mojoCoreAnyBuilder_;
    /**
     * <code>.mojo.core.Any mojo_core_any = 5;</code>
     * @return Whether the mojoCoreAny field is set.
     */
    @java.lang.Override
    public boolean hasMojoCoreAny() {
      return resultCase_ == 5;
    }
    /**
     * <code>.mojo.core.Any mojo_core_any = 5;</code>
     * @return The mojoCoreAny.
     */
    @java.lang.Override
    public org.mojolang.mojo.core.Any getMojoCoreAny() {
      if (mojoCoreAnyBuilder_ == null) {
        if (resultCase_ == 5) {
          return (org.mojolang.mojo.core.Any) result_;
        }
        return org.mojolang.mojo.core.Any.getDefaultInstance();
      } else {
        if (resultCase_ == 5) {
          return mojoCoreAnyBuilder_.getMessage();
        }
        return org.mojolang.mojo.core.Any.getDefaultInstance();
      }
    }
    /**
     * <code>.mojo.core.Any mojo_core_any = 5;</code>
     */
    public Builder setMojoCoreAny(org.mojolang.mojo.core.Any value) {
      if (mojoCoreAnyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        mojoCoreAnyBuilder_.setMessage(value);
      }
      resultCase_ = 5;
      return this;
    }
    /**
     * <code>.mojo.core.Any mojo_core_any = 5;</code>
     */
    public Builder setMojoCoreAny(
        org.mojolang.mojo.core.Any.Builder builderForValue) {
      if (mojoCoreAnyBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        mojoCoreAnyBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 5;
      return this;
    }
    /**
     * <code>.mojo.core.Any mojo_core_any = 5;</code>
     */
    public Builder mergeMojoCoreAny(org.mojolang.mojo.core.Any value) {
      if (mojoCoreAnyBuilder_ == null) {
        if (resultCase_ == 5 &&
            result_ != org.mojolang.mojo.core.Any.getDefaultInstance()) {
          result_ = org.mojolang.mojo.core.Any.newBuilder((org.mojolang.mojo.core.Any) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 5) {
          mojoCoreAnyBuilder_.mergeFrom(value);
        }
        mojoCoreAnyBuilder_.setMessage(value);
      }
      resultCase_ = 5;
      return this;
    }
    /**
     * <code>.mojo.core.Any mojo_core_any = 5;</code>
     */
    public Builder clearMojoCoreAny() {
      if (mojoCoreAnyBuilder_ == null) {
        if (resultCase_ == 5) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 5) {
          resultCase_ = 0;
          result_ = null;
        }
        mojoCoreAnyBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.mojo.core.Any mojo_core_any = 5;</code>
     */
    public org.mojolang.mojo.core.Any.Builder getMojoCoreAnyBuilder() {
      return getMojoCoreAnyFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.core.Any mojo_core_any = 5;</code>
     */
    @java.lang.Override
    public org.mojolang.mojo.core.AnyOrBuilder getMojoCoreAnyOrBuilder() {
      if ((resultCase_ == 5) && (mojoCoreAnyBuilder_ != null)) {
        return mojoCoreAnyBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 5) {
          return (org.mojolang.mojo.core.Any) result_;
        }
        return org.mojolang.mojo.core.Any.getDefaultInstance();
      }
    }
    /**
     * <code>.mojo.core.Any mojo_core_any = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Any, org.mojolang.mojo.core.Any.Builder, org.mojolang.mojo.core.AnyOrBuilder> 
        getMojoCoreAnyFieldBuilder() {
      if (mojoCoreAnyBuilder_ == null) {
        if (!(resultCase_ == 5)) {
          result_ = org.mojolang.mojo.core.Any.getDefaultInstance();
        }
        mojoCoreAnyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.core.Any, org.mojolang.mojo.core.Any.Builder, org.mojolang.mojo.core.AnyOrBuilder>(
                (org.mojolang.mojo.core.Any) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 5;
      onChanged();;
      return mojoCoreAnyBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.rpc.longrunning.Operation)
  }

  // @@protoc_insertion_point(class_scope:mojo.rpc.longrunning.Operation)
  private static final org.mojo-lang.mojo.rpc.longrunning.Operation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojo-lang.mojo.rpc.longrunning.Operation();
  }

  public static org.mojo-lang.mojo.rpc.longrunning.Operation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Operation>
      PARSER = new com.google.protobuf.AbstractParser<Operation>() {
    @java.lang.Override
    public Operation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Operation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Operation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Operation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojo-lang.mojo.rpc.longrunning.Operation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

