// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/rpc/longrunning/operation.proto

package org.mojo-lang.mojo.rpc.longrunning;

public interface OperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.rpc.longrunning.Operation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.mojo.core.Any metadata = 2;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.mojo.core.Any metadata = 2;</code>
   * @return The metadata.
   */
  org.mojolang.mojo.core.Any getMetadata();
  /**
   * <code>.mojo.core.Any metadata = 2;</code>
   */
  org.mojolang.mojo.core.AnyOrBuilder getMetadataOrBuilder();

  /**
   * <code>bool done = 3;</code>
   * @return The done.
   */
  boolean getDone();

  /**
   * <code>.mojo.core.Error mojo_core_error = 4;</code>
   * @return Whether the mojoCoreError field is set.
   */
  boolean hasMojoCoreError();
  /**
   * <code>.mojo.core.Error mojo_core_error = 4;</code>
   * @return The mojoCoreError.
   */
  org.mojolang.mojo.core.Error getMojoCoreError();
  /**
   * <code>.mojo.core.Error mojo_core_error = 4;</code>
   */
  org.mojolang.mojo.core.ErrorOrBuilder getMojoCoreErrorOrBuilder();

  /**
   * <code>.mojo.core.Any mojo_core_any = 5;</code>
   * @return Whether the mojoCoreAny field is set.
   */
  boolean hasMojoCoreAny();
  /**
   * <code>.mojo.core.Any mojo_core_any = 5;</code>
   * @return The mojoCoreAny.
   */
  org.mojolang.mojo.core.Any getMojoCoreAny();
  /**
   * <code>.mojo.core.Any mojo_core_any = 5;</code>
   */
  org.mojolang.mojo.core.AnyOrBuilder getMojoCoreAnyOrBuilder();

  public org.mojo-lang.mojo.rpc.longrunning.Operation.ResultCase getResultCase();
}
