// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/rpc/longrunning/operations.proto

package longrunning

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	core "github.com/mojo-lang/core/go/pkg/mojo/core"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListOperationsRequest struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Filter               string   `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize             int32    `protobuf:"varint,2000,opt,name=page_size,json=pageSize,proto3" json:"pageSize,omitempty"`
	PageToken            string   `protobuf:"bytes,2001,opt,name=page_token,json=pageToken,proto3" json:"pageToken,omitempty"`
	Skip                 int32    `protobuf:"varint,2002,opt,name=skip,proto3" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *ListOperationsRequest) Reset()         { *m = ListOperationsRequest{} }
func (m *ListOperationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListOperationsRequest) ProtoMessage()    {}
func (*ListOperationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dc651e5bb0b76d3, []int{0}
}
func (m *ListOperationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOperationsRequest.Unmarshal(m, b)
}
func (m *ListOperationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOperationsRequest.Marshal(b, m, deterministic)
}
func (m *ListOperationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOperationsRequest.Merge(m, src)
}
func (m *ListOperationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListOperationsRequest.Size(m)
}
func (m *ListOperationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOperationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOperationsRequest proto.InternalMessageInfo

func (m *ListOperationsRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListOperationsRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ListOperationsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListOperationsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *ListOperationsRequest) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

type ListOperationsResponse struct {
	Operations           []*Operation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	TotalCount           int32        `protobuf:"varint,2000,opt,name=total_count,json=totalCount,proto3" json:"totalCount,omitempty"`
	NextPageToken        string       `protobuf:"bytes,2001,opt,name=next_page_token,json=nextPageToken,proto3" json:"nextPageToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte       `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32        `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *ListOperationsResponse) Reset()         { *m = ListOperationsResponse{} }
func (m *ListOperationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListOperationsResponse) ProtoMessage()    {}
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dc651e5bb0b76d3, []int{1}
}
func (m *ListOperationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOperationsResponse.Unmarshal(m, b)
}
func (m *ListOperationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOperationsResponse.Marshal(b, m, deterministic)
}
func (m *ListOperationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOperationsResponse.Merge(m, src)
}
func (m *ListOperationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListOperationsResponse.Size(m)
}
func (m *ListOperationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOperationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOperationsResponse proto.InternalMessageInfo

func (m *ListOperationsResponse) GetOperations() []*Operation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *ListOperationsResponse) GetTotalCount() int32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListOperationsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetOperationRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *GetOperationRequest) Reset()         { *m = GetOperationRequest{} }
func (m *GetOperationRequest) String() string { return proto.CompactTextString(m) }
func (*GetOperationRequest) ProtoMessage()    {}
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dc651e5bb0b76d3, []int{2}
}
func (m *GetOperationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOperationRequest.Unmarshal(m, b)
}
func (m *GetOperationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOperationRequest.Marshal(b, m, deterministic)
}
func (m *GetOperationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOperationRequest.Merge(m, src)
}
func (m *GetOperationRequest) XXX_Size() int {
	return xxx_messageInfo_GetOperationRequest.Size(m)
}
func (m *GetOperationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOperationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOperationRequest proto.InternalMessageInfo

func (m *GetOperationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteOperationRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *DeleteOperationRequest) Reset()         { *m = DeleteOperationRequest{} }
func (m *DeleteOperationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteOperationRequest) ProtoMessage()    {}
func (*DeleteOperationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dc651e5bb0b76d3, []int{3}
}
func (m *DeleteOperationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOperationRequest.Unmarshal(m, b)
}
func (m *DeleteOperationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOperationRequest.Marshal(b, m, deterministic)
}
func (m *DeleteOperationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOperationRequest.Merge(m, src)
}
func (m *DeleteOperationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteOperationRequest.Size(m)
}
func (m *DeleteOperationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOperationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOperationRequest proto.InternalMessageInfo

func (m *DeleteOperationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CancelOperationRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *CancelOperationRequest) Reset()         { *m = CancelOperationRequest{} }
func (m *CancelOperationRequest) String() string { return proto.CompactTextString(m) }
func (*CancelOperationRequest) ProtoMessage()    {}
func (*CancelOperationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dc651e5bb0b76d3, []int{4}
}
func (m *CancelOperationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOperationRequest.Unmarshal(m, b)
}
func (m *CancelOperationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOperationRequest.Marshal(b, m, deterministic)
}
func (m *CancelOperationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOperationRequest.Merge(m, src)
}
func (m *CancelOperationRequest) XXX_Size() int {
	return xxx_messageInfo_CancelOperationRequest.Size(m)
}
func (m *CancelOperationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOperationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOperationRequest proto.InternalMessageInfo

func (m *CancelOperationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type WaitOperationRequest struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Timeout              *core.Duration `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte         `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32          `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *WaitOperationRequest) Reset()         { *m = WaitOperationRequest{} }
func (m *WaitOperationRequest) String() string { return proto.CompactTextString(m) }
func (*WaitOperationRequest) ProtoMessage()    {}
func (*WaitOperationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dc651e5bb0b76d3, []int{5}
}
func (m *WaitOperationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitOperationRequest.Unmarshal(m, b)
}
func (m *WaitOperationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitOperationRequest.Marshal(b, m, deterministic)
}
func (m *WaitOperationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitOperationRequest.Merge(m, src)
}
func (m *WaitOperationRequest) XXX_Size() int {
	return xxx_messageInfo_WaitOperationRequest.Size(m)
}
func (m *WaitOperationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitOperationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WaitOperationRequest proto.InternalMessageInfo

func (m *WaitOperationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WaitOperationRequest) GetTimeout() *core.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func init() {
	proto.RegisterType((*ListOperationsRequest)(nil), "mojo.rpc.longrunning.ListOperationsRequest")
	proto.RegisterType((*ListOperationsResponse)(nil), "mojo.rpc.longrunning.ListOperationsResponse")
	proto.RegisterType((*GetOperationRequest)(nil), "mojo.rpc.longrunning.GetOperationRequest")
	proto.RegisterType((*DeleteOperationRequest)(nil), "mojo.rpc.longrunning.DeleteOperationRequest")
	proto.RegisterType((*CancelOperationRequest)(nil), "mojo.rpc.longrunning.CancelOperationRequest")
	proto.RegisterType((*WaitOperationRequest)(nil), "mojo.rpc.longrunning.WaitOperationRequest")
}

func init() {
	proto.RegisterFile("mojo/rpc/longrunning/operations.proto", fileDescriptor_7dc651e5bb0b76d3)
}

var fileDescriptor_7dc651e5bb0b76d3 = []byte{
	// 600 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcf, 0x6b, 0xd4, 0x40,
	0x18, 0x35, 0x6d, 0xad, 0xf6, 0x2b, 0x6d, 0xea, 0x74, 0xdb, 0x86, 0x15, 0xcc, 0xb2, 0xf8, 0x63,
	0xd5, 0x9a, 0x40, 0x15, 0x04, 0x45, 0x28, 0xdb, 0x05, 0x2f, 0xa2, 0xb5, 0x0a, 0xa2, 0x22, 0x4b,
	0x1a, 0xc7, 0x38, 0xee, 0x64, 0x26, 0x26, 0x13, 0xd4, 0x82, 0x37, 0x6f, 0xfe, 0x03, 0xfe, 0x59,
	0xea, 0x59, 0x72, 0xf1, 0x96, 0xbb, 0x77, 0x99, 0x49, 0x76, 0x33, 0xda, 0xd1, 0x95, 0x7a, 0xdb,
	0x7d, 0x79, 0xef, 0xfb, 0x92, 0xf7, 0xde, 0x0c, 0x9c, 0x8b, 0xf9, 0x2b, 0xee, 0xa7, 0x49, 0xe8,
	0x53, 0xce, 0xa2, 0x34, 0x67, 0x8c, 0xb0, 0xc8, 0xe7, 0x09, 0x4e, 0x03, 0x41, 0x38, 0xcb, 0xbc,
	0x24, 0xe5, 0x82, 0xa3, 0x96, 0xa4, 0x79, 0x69, 0x12, 0x7a, 0x1a, 0xad, 0xad, 0x50, 0x3f, 0xe4,
	0x29, 0xf6, 0x59, 0x4e, 0x69, 0xc5, 0xd5, 0x51, 0x41, 0x62, 0x5c, 0xa3, 0x67, 0xff, 0xbe, 0xa8,
	0x62, 0x75, 0x3f, 0xce, 0xc0, 0xda, 0x1d, 0x92, 0x89, 0x7b, 0x93, 0x17, 0xd8, 0xc3, 0xaf, 0x73,
	0x9c, 0x09, 0xb4, 0x09, 0xf3, 0x49, 0x90, 0x62, 0x26, 0x1c, 0xab, 0x63, 0xf5, 0x16, 0xfa, 0xad,
	0xb2, 0x70, 0x57, 0x2a, 0x64, 0x93, 0xc7, 0x44, 0xe0, 0x38, 0x11, 0xef, 0xf6, 0x6a, 0x8e, 0x64,
	0xbf, 0x20, 0x54, 0xe0, 0xd4, 0x99, 0x6b, 0xd8, 0x15, 0xa2, 0xb3, 0x2b, 0x04, 0x5d, 0x83, 0x85,
	0x24, 0x88, 0xf0, 0x30, 0x23, 0x07, 0xd8, 0xf9, 0x6c, 0x77, 0xac, 0xde, 0xf1, 0xfe, 0x7a, 0x59,
	0xb8, 0x48, 0xa2, 0x0f, 0xc8, 0x01, 0xd6, 0x34, 0x27, 0xc7, 0x18, 0xba, 0x0e, 0xa0, 0x54, 0x82,
	0x8f, 0x30, 0x73, 0xbe, 0xd8, 0x6a, 0xd1, 0x46, 0x59, 0xb8, 0xab, 0x12, 0x7e, 0x28, 0x51, 0x4d,
	0xb7, 0x30, 0x01, 0xd1, 0x05, 0x98, 0xcb, 0x46, 0x24, 0x71, 0xbe, 0x56, 0x9b, 0x50, 0x59, 0xb8,
	0xcb, 0x12, 0xd0, 0xd8, 0x8a, 0xd0, 0xfd, 0x61, 0xc1, 0xfa, 0xef, 0x6e, 0x64, 0x09, 0x67, 0x19,
	0x46, 0x8f, 0x01, 0x9a, 0x90, 0x1c, 0xab, 0x33, 0xdb, 0x5b, 0xdc, 0x72, 0x3d, 0x53, 0x4a, 0xde,
	0x44, 0xdd, 0x77, 0xca, 0xc2, 0x6d, 0x35, 0x32, 0x6d, 0x9f, 0x36, 0x0c, 0xdd, 0x80, 0x45, 0xc1,
	0x45, 0x40, 0x87, 0x21, 0xcf, 0x99, 0x18, 0xfb, 0xa1, 0xb4, 0x0a, 0xdf, 0x91, 0xb0, 0xae, 0x6d,
	0x50, 0x34, 0x00, 0x9b, 0xe1, 0xb7, 0x62, 0x78, 0xd8, 0x98, 0xd3, 0x65, 0xe1, 0x6e, 0xc8, 0x67,
	0xbb, 0x06, 0x73, 0x96, 0x7e, 0x79, 0xd0, 0xbd, 0x05, 0xab, 0xb7, 0x71, 0xf3, 0xd5, 0xe3, 0x0a,
	0x9c, 0x87, 0x39, 0x16, 0xc4, 0xb8, 0x2e, 0x80, 0xb2, 0x4d, 0xfe, 0xd7, 0x6d, 0x93, 0xff, 0xbb,
	0xdb, 0xb0, 0x3e, 0xc0, 0x14, 0x0b, 0xfc, 0x3f, 0x13, 0x76, 0x02, 0x16, 0x62, 0x7a, 0xe4, 0x09,
	0x1f, 0x2c, 0x68, 0x3d, 0x0a, 0xc8, 0x91, 0x3f, 0x02, 0x0d, 0xe0, 0x84, 0x3c, 0x3d, 0x3c, 0x17,
	0xce, 0x4c, 0xc7, 0xea, 0x2d, 0x6e, 0xad, 0x56, 0xe9, 0xca, 0x73, 0xe5, 0x0d, 0xf2, 0x3a, 0xd1,
	0xb5, 0xb2, 0x70, 0x4f, 0xd5, 0x3c, 0x6d, 0xc4, 0x58, 0xba, 0xf5, 0x6d, 0x16, 0xa0, 0x69, 0x0f,
	0xa2, 0x60, 0x53, 0x92, 0x89, 0xa1, 0x96, 0xf6, 0x65, 0x73, 0x69, 0x8c, 0x87, 0xb0, 0xbd, 0xf9,
	0x6f, 0xe4, 0xba, 0xa3, 0x4f, 0x61, 0x29, 0xc2, 0xda, 0x32, 0x74, 0xd1, 0x2c, 0x37, 0x64, 0xdd,
	0x9e, 0xd6, 0x65, 0x74, 0x1f, 0x56, 0x9e, 0xab, 0x90, 0xb5, 0xf9, 0x7f, 0x78, 0x3d, 0x73, 0x19,
	0xda, 0xb6, 0x66, 0xe8, 0xdd, 0x9c, 0x52, 0x39, 0x32, 0x54, 0xa9, 0x4f, 0x1f, 0x69, 0x6e, 0xc7,
	0xe1, 0x91, 0xcf, 0x60, 0xf9, 0x4d, 0x40, 0x74, 0x0f, 0x2e, 0x99, 0x07, 0x9a, 0xba, 0x32, 0xd5,
	0x84, 0xfe, 0xfb, 0x4f, 0xdf, 0xcf, 0x1c, 0x83, 0x2e, 0x4f, 0x23, 0xc5, 0xbc, 0x42, 0x03, 0x16,
	0x19, 0x35, 0x7d, 0xbb, 0xc9, 0x67, 0x57, 0xde, 0xb4, 0xbb, 0xd6, 0x93, 0xed, 0x88, 0x88, 0x97,
	0xf9, 0xbe, 0x17, 0xf2, 0xd8, 0x9f, 0xa8, 0xd5, 0x0d, 0x1d, 0x71, 0x3f, 0x19, 0x45, 0xbe, 0xe9,
	0xc6, 0xbe, 0xa9, 0xfd, 0xde, 0x9f, 0x57, 0x97, 0xf6, 0xd5, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xf0, 0x36, 0x3f, 0x43, 0x45, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OperationsClient is the client API for Operations service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OperationsClient interface {
	ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (*ListOperationsResponse, error)
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error)
	DeleteOperation(ctx context.Context, in *DeleteOperationRequest, opts ...grpc.CallOption) (*core.Null, error)
	CancelOperation(ctx context.Context, in *CancelOperationRequest, opts ...grpc.CallOption) (*core.Null, error)
	WaitOperation(ctx context.Context, in *WaitOperationRequest, opts ...grpc.CallOption) (*Operation, error)
}

type operationsClient struct {
	cc *grpc.ClientConn
}

func NewOperationsClient(cc *grpc.ClientConn) OperationsClient {
	return &operationsClient{cc}
}

func (c *operationsClient) ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (*ListOperationsResponse, error) {
	out := new(ListOperationsResponse)
	err := c.cc.Invoke(ctx, "/mojo.rpc.longrunning.Operations/list_operations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	out := new(Operation)
	err := c.cc.Invoke(ctx, "/mojo.rpc.longrunning.Operations/get_operation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsClient) DeleteOperation(ctx context.Context, in *DeleteOperationRequest, opts ...grpc.CallOption) (*core.Null, error) {
	out := new(core.Null)
	err := c.cc.Invoke(ctx, "/mojo.rpc.longrunning.Operations/delete_operation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsClient) CancelOperation(ctx context.Context, in *CancelOperationRequest, opts ...grpc.CallOption) (*core.Null, error) {
	out := new(core.Null)
	err := c.cc.Invoke(ctx, "/mojo.rpc.longrunning.Operations/cancel_operation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operationsClient) WaitOperation(ctx context.Context, in *WaitOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	out := new(Operation)
	err := c.cc.Invoke(ctx, "/mojo.rpc.longrunning.Operations/wait_operation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationsServer is the server API for Operations service.
type OperationsServer interface {
	ListOperations(context.Context, *ListOperationsRequest) (*ListOperationsResponse, error)
	GetOperation(context.Context, *GetOperationRequest) (*Operation, error)
	DeleteOperation(context.Context, *DeleteOperationRequest) (*core.Null, error)
	CancelOperation(context.Context, *CancelOperationRequest) (*core.Null, error)
	WaitOperation(context.Context, *WaitOperationRequest) (*Operation, error)
}

// UnimplementedOperationsServer can be embedded to have forward compatible implementations.
type UnimplementedOperationsServer struct {
}

func (*UnimplementedOperationsServer) ListOperations(ctx context.Context, req *ListOperationsRequest) (*ListOperationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOperations not implemented")
}
func (*UnimplementedOperationsServer) GetOperation(ctx context.Context, req *GetOperationRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperation not implemented")
}
func (*UnimplementedOperationsServer) DeleteOperation(ctx context.Context, req *DeleteOperationRequest) (*core.Null, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOperation not implemented")
}
func (*UnimplementedOperationsServer) CancelOperation(ctx context.Context, req *CancelOperationRequest) (*core.Null, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOperation not implemented")
}
func (*UnimplementedOperationsServer) WaitOperation(ctx context.Context, req *WaitOperationRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitOperation not implemented")
}

func RegisterOperationsServer(s *grpc.Server, srv OperationsServer) {
	s.RegisterService(&_Operations_serviceDesc, srv)
}

func _Operations_ListOperations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServer).ListOperations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mojo.rpc.longrunning.Operations/ListOperations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServer).ListOperations(ctx, req.(*ListOperationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operations_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mojo.rpc.longrunning.Operations/GetOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operations_DeleteOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServer).DeleteOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mojo.rpc.longrunning.Operations/DeleteOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServer).DeleteOperation(ctx, req.(*DeleteOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operations_CancelOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServer).CancelOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mojo.rpc.longrunning.Operations/CancelOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServer).CancelOperation(ctx, req.(*CancelOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operations_WaitOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationsServer).WaitOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mojo.rpc.longrunning.Operations/WaitOperation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationsServer).WaitOperation(ctx, req.(*WaitOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Operations_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mojo.rpc.longrunning.Operations",
	HandlerType: (*OperationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "list_operations",
			Handler:    _Operations_ListOperations_Handler,
		},
		{
			MethodName: "get_operation",
			Handler:    _Operations_GetOperation_Handler,
		},
		{
			MethodName: "delete_operation",
			Handler:    _Operations_DeleteOperation_Handler,
		},
		{
			MethodName: "cancel_operation",
			Handler:    _Operations_CancelOperation_Handler,
		},
		{
			MethodName: "wait_operation",
			Handler:    _Operations_WaitOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mojo/rpc/longrunning/operations.proto",
}
