// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/rpc/attribute_context.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	core "github.com/mojo-lang/core/go/pkg/mojo/core"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AttributeContext struct {
	Origin               *AttributeContext_Peer     `protobuf:"bytes,7,opt,name=origin,proto3" json:"origin,omitempty"`
	Source               *AttributeContext_Peer     `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination          *AttributeContext_Peer     `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Request              *AttributeContext_Request  `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Response             *AttributeContext_Response `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	Resource             *AttributeContext_Resource `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	Api                  *AttributeContext_Api      `protobuf:"bytes,6,opt,name=api,proto3" json:"api,omitempty"`
	Extensions           []*core.Any                `protobuf:"bytes,8,rep,name=extensions,proto3" json:"extensions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte                     `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32                      `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *AttributeContext) Reset()         { *m = AttributeContext{} }
func (m *AttributeContext) String() string { return proto.CompactTextString(m) }
func (*AttributeContext) ProtoMessage()    {}
func (*AttributeContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_951b9de76397385e, []int{0}
}
func (m *AttributeContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeContext.Unmarshal(m, b)
}
func (m *AttributeContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeContext.Marshal(b, m, deterministic)
}
func (m *AttributeContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeContext.Merge(m, src)
}
func (m *AttributeContext) XXX_Size() int {
	return xxx_messageInfo_AttributeContext.Size(m)
}
func (m *AttributeContext) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeContext.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeContext proto.InternalMessageInfo

func (m *AttributeContext) GetOrigin() *AttributeContext_Peer {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *AttributeContext) GetSource() *AttributeContext_Peer {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *AttributeContext) GetDestination() *AttributeContext_Peer {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *AttributeContext) GetRequest() *AttributeContext_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *AttributeContext) GetResponse() *AttributeContext_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *AttributeContext) GetResource() *AttributeContext_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *AttributeContext) GetApi() *AttributeContext_Api {
	if m != nil {
		return m.Api
	}
	return nil
}

func (m *AttributeContext) GetExtensions() []*core.Any {
	if m != nil {
		return m.Extensions
	}
	return nil
}

type AttributeContext_Peer struct {
	Ip                   string            `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int64             `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Labels               map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Principal            string            `protobuf:"bytes,7,opt,name=principal,proto3" json:"principal,omitempty"`
	RegionCode           string            `protobuf:"bytes,8,opt,name=region_code,json=regionCode,proto3" json:"regionCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *AttributeContext_Peer) Reset()         { *m = AttributeContext_Peer{} }
func (m *AttributeContext_Peer) String() string { return proto.CompactTextString(m) }
func (*AttributeContext_Peer) ProtoMessage()    {}
func (*AttributeContext_Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_951b9de76397385e, []int{0, 0}
}
func (m *AttributeContext_Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeContext_Peer.Unmarshal(m, b)
}
func (m *AttributeContext_Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeContext_Peer.Marshal(b, m, deterministic)
}
func (m *AttributeContext_Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeContext_Peer.Merge(m, src)
}
func (m *AttributeContext_Peer) XXX_Size() int {
	return xxx_messageInfo_AttributeContext_Peer.Size(m)
}
func (m *AttributeContext_Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeContext_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeContext_Peer proto.InternalMessageInfo

func (m *AttributeContext_Peer) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AttributeContext_Peer) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *AttributeContext_Peer) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *AttributeContext_Peer) GetPrincipal() string {
	if m != nil {
		return m.Principal
	}
	return ""
}

func (m *AttributeContext_Peer) GetRegionCode() string {
	if m != nil {
		return m.RegionCode
	}
	return ""
}

type AttributeContext_Api struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Operation            string   `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Protocol             string   `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *AttributeContext_Api) Reset()         { *m = AttributeContext_Api{} }
func (m *AttributeContext_Api) String() string { return proto.CompactTextString(m) }
func (*AttributeContext_Api) ProtoMessage()    {}
func (*AttributeContext_Api) Descriptor() ([]byte, []int) {
	return fileDescriptor_951b9de76397385e, []int{0, 1}
}
func (m *AttributeContext_Api) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeContext_Api.Unmarshal(m, b)
}
func (m *AttributeContext_Api) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeContext_Api.Marshal(b, m, deterministic)
}
func (m *AttributeContext_Api) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeContext_Api.Merge(m, src)
}
func (m *AttributeContext_Api) XXX_Size() int {
	return xxx_messageInfo_AttributeContext_Api.Size(m)
}
func (m *AttributeContext_Api) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeContext_Api.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeContext_Api proto.InternalMessageInfo

func (m *AttributeContext_Api) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *AttributeContext_Api) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *AttributeContext_Api) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *AttributeContext_Api) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type AttributeContext_Auth struct {
	Principal            string       `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Audiences            []string     `protobuf:"bytes,2,rep,name=audiences,proto3" json:"audiences,omitempty"`
	Presenter            string       `protobuf:"bytes,3,opt,name=presenter,proto3" json:"presenter,omitempty"`
	Claims               *core.Object `protobuf:"bytes,4,opt,name=claims,proto3" json:"claims,omitempty"`
	AccessLevels         []string     `protobuf:"bytes,5,rep,name=access_levels,json=accessLevels,proto3" json:"accessLevels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte       `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32        `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *AttributeContext_Auth) Reset()         { *m = AttributeContext_Auth{} }
func (m *AttributeContext_Auth) String() string { return proto.CompactTextString(m) }
func (*AttributeContext_Auth) ProtoMessage()    {}
func (*AttributeContext_Auth) Descriptor() ([]byte, []int) {
	return fileDescriptor_951b9de76397385e, []int{0, 2}
}
func (m *AttributeContext_Auth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeContext_Auth.Unmarshal(m, b)
}
func (m *AttributeContext_Auth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeContext_Auth.Marshal(b, m, deterministic)
}
func (m *AttributeContext_Auth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeContext_Auth.Merge(m, src)
}
func (m *AttributeContext_Auth) XXX_Size() int {
	return xxx_messageInfo_AttributeContext_Auth.Size(m)
}
func (m *AttributeContext_Auth) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeContext_Auth.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeContext_Auth proto.InternalMessageInfo

func (m *AttributeContext_Auth) GetPrincipal() string {
	if m != nil {
		return m.Principal
	}
	return ""
}

func (m *AttributeContext_Auth) GetAudiences() []string {
	if m != nil {
		return m.Audiences
	}
	return nil
}

func (m *AttributeContext_Auth) GetPresenter() string {
	if m != nil {
		return m.Presenter
	}
	return ""
}

func (m *AttributeContext_Auth) GetClaims() *core.Object {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *AttributeContext_Auth) GetAccessLevels() []string {
	if m != nil {
		return m.AccessLevels
	}
	return nil
}

type AttributeContext_Request struct {
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method               string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers              map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Path                 string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Host                 string                 `protobuf:"bytes,5,opt,name=host,proto3" json:"host,omitempty"`
	Scheme               string                 `protobuf:"bytes,6,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Query                string                 `protobuf:"bytes,7,opt,name=query,proto3" json:"query,omitempty"`
	Time                 *core.Timestamp        `protobuf:"bytes,9,opt,name=time,proto3" json:"time,omitempty"`
	Size_                int64                  `protobuf:"varint,10,opt,name=size,proto3" json:"size,omitempty"`
	Protocol             string                 `protobuf:"bytes,11,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Reason               string                 `protobuf:"bytes,12,opt,name=reason,proto3" json:"reason,omitempty"`
	Auth                 *AttributeContext_Auth `protobuf:"bytes,13,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte                 `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32                  `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *AttributeContext_Request) Reset()         { *m = AttributeContext_Request{} }
func (m *AttributeContext_Request) String() string { return proto.CompactTextString(m) }
func (*AttributeContext_Request) ProtoMessage()    {}
func (*AttributeContext_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_951b9de76397385e, []int{0, 3}
}
func (m *AttributeContext_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeContext_Request.Unmarshal(m, b)
}
func (m *AttributeContext_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeContext_Request.Marshal(b, m, deterministic)
}
func (m *AttributeContext_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeContext_Request.Merge(m, src)
}
func (m *AttributeContext_Request) XXX_Size() int {
	return xxx_messageInfo_AttributeContext_Request.Size(m)
}
func (m *AttributeContext_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeContext_Request.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeContext_Request proto.InternalMessageInfo

func (m *AttributeContext_Request) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AttributeContext_Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *AttributeContext_Request) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *AttributeContext_Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *AttributeContext_Request) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *AttributeContext_Request) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *AttributeContext_Request) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *AttributeContext_Request) GetTime() *core.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *AttributeContext_Request) GetSize_() int64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *AttributeContext_Request) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *AttributeContext_Request) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *AttributeContext_Request) GetAuth() *AttributeContext_Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type AttributeContext_Response struct {
	Code                 int64             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Size_                int64             `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Headers              map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Time                 *core.Timestamp   `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	BackendLatency       *core.Duration    `protobuf:"bytes,5,opt,name=backend_latency,json=backendLatency,proto3" json:"backendLatency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *AttributeContext_Response) Reset()         { *m = AttributeContext_Response{} }
func (m *AttributeContext_Response) String() string { return proto.CompactTextString(m) }
func (*AttributeContext_Response) ProtoMessage()    {}
func (*AttributeContext_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_951b9de76397385e, []int{0, 4}
}
func (m *AttributeContext_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeContext_Response.Unmarshal(m, b)
}
func (m *AttributeContext_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeContext_Response.Marshal(b, m, deterministic)
}
func (m *AttributeContext_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeContext_Response.Merge(m, src)
}
func (m *AttributeContext_Response) XXX_Size() int {
	return xxx_messageInfo_AttributeContext_Response.Size(m)
}
func (m *AttributeContext_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeContext_Response.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeContext_Response proto.InternalMessageInfo

func (m *AttributeContext_Response) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AttributeContext_Response) GetSize_() int64 {
	if m != nil {
		return m.Size_
	}
	return 0
}

func (m *AttributeContext_Response) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *AttributeContext_Response) GetTime() *core.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *AttributeContext_Response) GetBackendLatency() *core.Duration {
	if m != nil {
		return m.BackendLatency
	}
	return nil
}

type AttributeContext_Resource struct {
	Service              string            `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Labels               map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Uid                  string            `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Annotations          map[string]string `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DisplayName          string            `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"displayName,omitempty"`
	CreateTime           *core.Timestamp   `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           *core.Timestamp   `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"updateTime,omitempty"`
	DeleteTime           *core.Timestamp   `protobuf:"bytes,10,opt,name=delete_time,json=deleteTime,proto3" json:"deleteTime,omitempty"`
	Etag                 string            `protobuf:"bytes,11,opt,name=etag,proto3" json:"etag,omitempty"`
	Location             string            `protobuf:"bytes,12,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte            `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32             `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *AttributeContext_Resource) Reset()         { *m = AttributeContext_Resource{} }
func (m *AttributeContext_Resource) String() string { return proto.CompactTextString(m) }
func (*AttributeContext_Resource) ProtoMessage()    {}
func (*AttributeContext_Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_951b9de76397385e, []int{0, 5}
}
func (m *AttributeContext_Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeContext_Resource.Unmarshal(m, b)
}
func (m *AttributeContext_Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeContext_Resource.Marshal(b, m, deterministic)
}
func (m *AttributeContext_Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeContext_Resource.Merge(m, src)
}
func (m *AttributeContext_Resource) XXX_Size() int {
	return xxx_messageInfo_AttributeContext_Resource.Size(m)
}
func (m *AttributeContext_Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeContext_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeContext_Resource proto.InternalMessageInfo

func (m *AttributeContext_Resource) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *AttributeContext_Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AttributeContext_Resource) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AttributeContext_Resource) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *AttributeContext_Resource) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AttributeContext_Resource) GetAnnotations() map[string]string {
	if m != nil {
		return m.Annotations
	}
	return nil
}

func (m *AttributeContext_Resource) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *AttributeContext_Resource) GetCreateTime() *core.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *AttributeContext_Resource) GetUpdateTime() *core.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *AttributeContext_Resource) GetDeleteTime() *core.Timestamp {
	if m != nil {
		return m.DeleteTime
	}
	return nil
}

func (m *AttributeContext_Resource) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *AttributeContext_Resource) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func init() {
	proto.RegisterType((*AttributeContext)(nil), "mojo.rpc.AttributeContext")
	proto.RegisterType((*AttributeContext_Peer)(nil), "mojo.rpc.AttributeContext.Peer")
	proto.RegisterMapType((map[string]string)(nil), "mojo.rpc.AttributeContext.Peer.LabelsEntry")
	proto.RegisterType((*AttributeContext_Api)(nil), "mojo.rpc.AttributeContext.Api")
	proto.RegisterType((*AttributeContext_Auth)(nil), "mojo.rpc.AttributeContext.Auth")
	proto.RegisterType((*AttributeContext_Request)(nil), "mojo.rpc.AttributeContext.Request")
	proto.RegisterMapType((map[string]string)(nil), "mojo.rpc.AttributeContext.Request.HeadersEntry")
	proto.RegisterType((*AttributeContext_Response)(nil), "mojo.rpc.AttributeContext.Response")
	proto.RegisterMapType((map[string]string)(nil), "mojo.rpc.AttributeContext.Response.HeadersEntry")
	proto.RegisterType((*AttributeContext_Resource)(nil), "mojo.rpc.AttributeContext.Resource")
	proto.RegisterMapType((map[string]string)(nil), "mojo.rpc.AttributeContext.Resource.AnnotationsEntry")
	proto.RegisterMapType((map[string]string)(nil), "mojo.rpc.AttributeContext.Resource.LabelsEntry")
}

func init() { proto.RegisterFile("mojo/rpc/attribute_context.proto", fileDescriptor_951b9de76397385e) }

var fileDescriptor_951b9de76397385e = []byte{
	// 1283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xcf, 0x8e, 0x1b, 0xc5,
	0x13, 0xfe, 0xf9, 0xcf, 0x7a, 0xed, 0xf6, 0x26, 0xd9, 0xf4, 0xee, 0xe6, 0x37, 0x58, 0x90, 0x59,
	0x25, 0x52, 0x14, 0xc4, 0x62, 0xa3, 0x40, 0x24, 0xfe, 0x44, 0x8a, 0xd6, 0x01, 0x91, 0x43, 0x20,
	0x51, 0x88, 0x84, 0x88, 0x40, 0x4b, 0x7b, 0xa6, 0xb0, 0x3b, 0x6b, 0x4f, 0x4f, 0x7a, 0x7a, 0x56,
	0x19, 0x4e, 0x3c, 0x06, 0x77, 0xce, 0x3c, 0x01, 0x6f, 0xc1, 0x0d, 0x0e, 0xbe, 0x70, 0x9b, 0xa7,
	0x40, 0x5d, 0xdd, 0x33, 0xd3, 0xe3, 0xc3, 0xda, 0x8b, 0x94, 0x1c, 0xfb, 0xeb, 0xaa, 0xaf, 0x6b,
	0xaa, 0xbe, 0xaa, 0xee, 0x21, 0x87, 0x0b, 0xf1, 0x42, 0x8c, 0x64, 0x1c, 0x8c, 0x98, 0x52, 0x92,
	0x4f, 0x52, 0x05, 0x27, 0x81, 0x88, 0x14, 0xbc, 0x52, 0xc3, 0x58, 0x0a, 0x25, 0x68, 0x57, 0x5b,
	0x0c, 0x65, 0x1c, 0x0c, 0xf6, 0xd0, 0x36, 0x10, 0x12, 0x46, 0x2c, 0xca, 0xcc, 0xf6, 0x60, 0xbf,
	0x02, 0x15, 0x5f, 0x80, 0x45, 0x0f, 0x2a, 0xf4, 0x8c, 0xcd, 0x53, 0x0b, 0xdf, 0xf8, 0xed, 0x1d,
	0xb2, 0x7b, 0x5c, 0x9c, 0xf3, 0xc0, 0x1c, 0x43, 0xbf, 0x22, 0x1d, 0x21, 0xf9, 0x94, 0x47, 0xde,
	0xf6, 0x61, 0xe3, 0x76, 0xff, 0x8e, 0x3f, 0x2c, 0x4e, 0x1c, 0xae, 0xda, 0x0e, 0x9f, 0x00, 0xc8,
	0xf1, 0x7e, 0xbe, 0xf4, 0x77, 0x8d, 0xcb, 0x91, 0x58, 0x70, 0x05, 0x8b, 0x58, 0x65, 0x4f, 0x2d,
	0x89, 0xa6, 0x4b, 0x44, 0x2a, 0x03, 0xf0, 0x1a, 0x17, 0xa0, 0x33, 0x2e, 0x2e, 0x9d, 0x41, 0xe8,
	0xf7, 0xa4, 0x1f, 0x42, 0xa2, 0x78, 0xc4, 0x14, 0x17, 0x91, 0xd7, 0xdc, 0x8c, 0xf3, 0xad, 0x7c,
	0xe9, 0x1f, 0x38, 0x7e, 0x0e, 0xb1, 0x4b, 0x47, 0xbf, 0x21, 0xdb, 0x12, 0x5e, 0xa6, 0x90, 0x28,
	0xaf, 0x85, 0xcc, 0x37, 0xce, 0x61, 0x7e, 0x6a, 0x2c, 0xc7, 0x07, 0xf9, 0xd2, 0xbf, 0x6a, 0xdd,
	0x1c, 0xe2, 0x82, 0x89, 0x7e, 0x4b, 0xba, 0x12, 0x92, 0x58, 0x44, 0x09, 0x78, 0x6d, 0x64, 0xbd,
	0x79, 0x2e, 0xab, 0x31, 0x1d, 0x5f, 0xcb, 0x97, 0x3e, 0x2d, 0x1c, 0x1d, 0xde, 0x92, 0xcc, 0x12,
	0x9b, 0xe4, 0x6e, 0x6d, 0x42, 0x8c, 0xa6, 0x25, 0xf1, 0x6a, 0x8a, 0x4b, 0x32, 0xfa, 0x80, 0xb4,
	0x58, 0xcc, 0xbd, 0x0e, 0x72, 0x5e, 0x3f, 0x87, 0xf3, 0x38, 0xe6, 0xe3, 0xab, 0xf9, 0xd2, 0xbf,
	0xc4, 0x62, 0xee, 0x30, 0x69, 0x6f, 0xfa, 0x90, 0x10, 0x78, 0xa5, 0x20, 0x4a, 0xb8, 0x88, 0x12,
	0xaf, 0x7b, 0xd8, 0xba, 0xdd, 0xbf, 0x73, 0xd9, 0x70, 0x69, 0x21, 0x0e, 0x8f, 0xa3, 0x6c, 0xec,
	0xe5, 0x4b, 0x7f, 0xbf, 0xb2, 0x72, 0x28, 0x1c, 0xdf, 0xc1, 0x2f, 0x2d, 0xd2, 0xd6, 0x65, 0xa4,
	0x87, 0xa4, 0xc9, 0x63, 0xd4, 0x51, 0x6f, 0xbc, 0x9b, 0x2f, 0xfd, 0x1d, 0x1e, 0x3b, 0x2e, 0x4d,
	0x1e, 0xd3, 0x5b, 0xa4, 0x1d, 0x0b, 0xa9, 0x50, 0x17, 0xad, 0x31, 0xcd, 0x97, 0xfe, 0x65, 0xbd,
	0x76, 0xac, 0x70, 0x9f, 0x7e, 0x47, 0x3a, 0x73, 0x36, 0x81, 0x79, 0xe2, 0x75, 0x30, 0xb0, 0xf7,
	0xd6, 0x28, 0x68, 0xf8, 0x08, 0xad, 0xbf, 0x88, 0x94, 0xcc, 0x8c, 0x42, 0x8d, 0xbb, 0xab, 0x50,
	0x83, 0xd0, 0xbb, 0xa4, 0x17, 0x4b, 0x1e, 0x05, 0x3c, 0x66, 0x73, 0x6c, 0xa1, 0xde, 0xf8, 0xff,
	0xf9, 0xd2, 0xdf, 0x2b, 0x41, 0xc7, 0xa7, 0xb2, 0xa4, 0x9f, 0x90, 0xbe, 0x84, 0x29, 0x17, 0xd1,
	0x49, 0x20, 0x42, 0xf0, 0xba, 0xe8, 0x88, 0xf9, 0x31, 0xf0, 0x03, 0x11, 0xba, 0xc5, 0x22, 0x15,
	0x3a, 0x60, 0xa4, 0xef, 0x84, 0x47, 0x6f, 0x92, 0xd6, 0x29, 0x64, 0x36, 0x4d, 0x58, 0x9d, 0x53,
	0xc8, 0xdc, 0xea, 0x9c, 0x42, 0x46, 0xdf, 0x25, 0x5b, 0x38, 0x09, 0x30, 0x53, 0xbd, 0xf1, 0x5e,
	0xbe, 0xf4, 0xaf, 0x20, 0xe0, 0x18, 0x1a, 0x8b, 0x4f, 0x9b, 0x1f, 0x37, 0x06, 0x7f, 0x36, 0x48,
	0xeb, 0x38, 0xe6, 0x74, 0x44, 0xb6, 0x13, 0x90, 0x67, 0xdc, 0xb6, 0x73, 0xcf, 0x88, 0xdf, 0x42,
	0xae, 0xf8, 0x2d, 0xa4, 0xb3, 0x21, 0x62, 0x90, 0x55, 0xb7, 0xda, 0x6c, 0x94, 0xa0, 0x9b, 0x8d,
	0x12, 0xa4, 0x77, 0x48, 0x17, 0x47, 0x54, 0x20, 0xe6, 0xd8, 0x89, 0x3d, 0xa3, 0xda, 0x02, 0x73,
	0x55, 0x5b, 0x60, 0x3a, 0xb6, 0x33, 0x90, 0x5a, 0x32, 0xd8, 0x66, 0x36, 0x36, 0x0b, 0xb9, 0xb1,
	0x59, 0x68, 0xf0, 0x7b, 0x93, 0xb4, 0x8f, 0x53, 0x35, 0xab, 0x97, 0xac, 0xb1, 0x71, 0xc9, 0xee,
	0x92, 0x1e, 0x4b, 0x43, 0x0e, 0x51, 0x00, 0x89, 0xd7, 0x3c, 0x6c, 0x15, 0x6e, 0x25, 0xe8, 0xba,
	0x95, 0xa0, 0x39, 0x0d, 0x12, 0x88, 0x14, 0x48, 0xfb, 0x71, 0xf6, 0x34, 0x0b, 0xd6, 0x4f, 0xb3,
	0x20, 0xbd, 0x4f, 0x3a, 0xc1, 0x9c, 0xf1, 0x45, 0x62, 0x87, 0xc8, 0x55, 0xa7, 0x97, 0x1e, 0x4f,
	0x5e, 0x40, 0xa0, 0x8c, 0x30, 0x8d, 0x91, 0x2b, 0x4c, 0x83, 0xd0, 0xfb, 0xe4, 0x12, 0x0b, 0x02,
	0x48, 0x92, 0x93, 0x39, 0x9c, 0x69, 0xe9, 0x6f, 0x61, 0xc8, 0x83, 0x7c, 0xe9, 0x5f, 0x33, 0x1b,
	0x8f, 0x10, 0x77, 0x5c, 0x77, 0x5c, 0x7c, 0xf0, 0xd7, 0x16, 0xd9, 0xb6, 0x43, 0x0f, 0x5b, 0x31,
	0xac, 0xb5, 0x62, 0x58, 0x6b, 0xc5, 0x90, 0x1e, 0x91, 0xce, 0x02, 0xd4, 0x4c, 0x84, 0xb6, 0xec,
	0x18, 0x9c, 0x41, 0xdc, 0xe0, 0x0c, 0x42, 0x7f, 0x24, 0xdb, 0x33, 0x60, 0x21, 0xc8, 0xc4, 0x6b,
	0x61, 0x47, 0x8e, 0xd6, 0x4f, 0xde, 0xe1, 0x43, 0xe3, 0x61, 0xba, 0x12, 0xab, 0x6d, 0x39, 0xdc,
	0x6a, 0x5b, 0x08, 0x47, 0x03, 0x53, 0x33, 0xab, 0x0d, 0x33, 0x1a, 0x98, 0x9a, 0xd5, 0x46, 0x03,
	0x53, 0x33, 0x6d, 0x37, 0x13, 0x89, 0xc2, 0x89, 0x6a, 0xed, 0xf4, 0xda, 0xb5, 0xd3, 0x6b, 0xfd,
	0x7d, 0x49, 0x30, 0x83, 0x05, 0xe0, 0x9c, 0xb4, 0xdf, 0x67, 0x90, 0xda, 0xbd, 0x85, 0x88, 0xee,
	0xb7, 0x97, 0x29, 0xc8, 0xcc, 0x4e, 0x04, 0xec, 0x37, 0x04, 0xdc, 0x7e, 0x43, 0x80, 0xde, 0x23,
	0x6d, 0x7d, 0x75, 0x7b, 0x3d, 0x2c, 0xf3, 0xbe, 0x53, 0xe6, 0x67, 0x7c, 0x01, 0x89, 0x62, 0x8b,
	0xd8, 0x84, 0xa5, 0xad, 0xdc, 0xb0, 0xf4, 0x5a, 0x87, 0x9f, 0xf0, 0x9f, 0xc1, 0x23, 0xd5, 0x04,
	0xd4, 0x6b, 0xd7, 0x4e, 0xaf, 0x6b, 0x1d, 0xd6, 0xdf, 0xb0, 0xc3, 0x8e, 0x48, 0x47, 0x02, 0x4b,
	0x44, 0xe4, 0xed, 0x54, 0x9f, 0x6c, 0x10, 0xf7, 0x93, 0x0d, 0x42, 0xbf, 0x24, 0x6d, 0x96, 0xaa,
	0x99, 0x77, 0x69, 0xed, 0x1d, 0xad, 0x9b, 0xd0, 0x84, 0xaa, 0x1d, 0xdc, 0x50, 0xf5, 0x7a, 0x30,
	0x21, 0x3b, 0x6e, 0xa5, 0x5f, 0xcb, 0x80, 0xfb, 0xa3, 0x45, 0xba, 0xc5, 0xd5, 0xab, 0x73, 0x88,
	0x43, 0xb8, 0x51, 0xe5, 0x30, 0xa8, 0x8f, 0x5f, 0xdc, 0x2f, 0x73, 0xdd, 0x5c, 0x93, 0x6b, 0xb6,
	0x2a, 0xee, 0x0f, 0x36, 0x78, 0x00, 0x5c, 0x4c, 0xdd, 0x85, 0x68, 0xda, 0xff, 0x49, 0x34, 0xcf,
	0xc9, 0x95, 0x09, 0x0b, 0x4e, 0x21, 0x0a, 0x4f, 0xe6, 0x4c, 0x41, 0x14, 0x64, 0xf6, 0x41, 0xb1,
	0xe7, 0x10, 0x7d, 0x9e, 0x9a, 0xe1, 0x3c, 0x7e, 0x3b, 0x5f, 0xfa, 0x9e, 0xb5, 0x7f, 0x64, 0xcc,
	0x1d, 0xc6, 0xcb, 0xf5, 0x9d, 0x37, 0x52, 0xbd, 0xbf, 0xb7, 0xb1, 0x7a, 0xe6, 0xf5, 0x72, 0xe1,
	0x3b, 0xea, 0x16, 0x69, 0x47, 0x6c, 0x51, 0x9c, 0x85, 0x59, 0xd2, 0x6b, 0x37, 0x4b, 0x7a, 0xad,
	0xed, 0x54, 0x16, 0x83, 0x9d, 0xd9, 0x26, 0x9b, 0x59, 0x5c, 0xcf, 0x66, 0x16, 0x03, 0xfd, 0xa1,
	0x7c, 0x5c, 0xb4, 0x37, 0x18, 0x65, 0x26, 0xea, 0x0b, 0x3c, 0x30, 0x6e, 0x92, 0x56, 0xca, 0x43,
	0x3b, 0x9f, 0x30, 0x81, 0x69, 0x6d, 0xf8, 0xea, 0x5d, 0xfa, 0x92, 0xf4, 0x59, 0x14, 0x09, 0x85,
	0x15, 0x2b, 0x5e, 0x39, 0x1f, 0x6d, 0x12, 0xc8, 0x71, 0xe5, 0x66, 0xa2, 0xc1, 0xc7, 0xb3, 0x43,
	0xe6, 0x3e, 0x9e, 0x1d, 0x98, 0xde, 0x23, 0x3b, 0x21, 0x4f, 0xe2, 0x39, 0xcb, 0x4e, 0x30, 0x9d,
	0x66, 0xd2, 0x99, 0xa7, 0xb7, 0xc1, 0xbf, 0xae, 0x67, 0xb5, 0xef, 0xc0, 0xf4, 0x31, 0xe9, 0x07,
	0x12, 0x98, 0x82, 0x13, 0xd4, 0x71, 0xf7, 0x1c, 0x1d, 0xe3, 0xab, 0xc8, 0x18, 0x3f, 0xab, 0xab,
	0x99, 0x54, 0xa8, 0x26, 0x4c, 0xe3, 0xb0, 0x24, 0xec, 0xad, 0x23, 0x34, 0xc6, 0xab, 0x84, 0x15,
	0xaa, 0x09, 0x43, 0x98, 0x43, 0x41, 0x48, 0xd6, 0x11, 0x1a, 0xe3, 0x55, 0xc2, 0x0a, 0xd5, 0x7a,
	0x02, 0xc5, 0xa6, 0x76, 0xfc, 0xa2, 0x9e, 0xf4, 0xda, 0xd5, 0x93, 0x5e, 0xeb, 0x51, 0x3d, 0x17,
	0x81, 0x79, 0x42, 0xed, 0x54, 0xa3, 0xba, 0xc0, 0xdc, 0x51, 0x5d, 0x60, 0x6f, 0xe2, 0x4d, 0xf8,
	0x13, 0xd9, 0x5d, 0xd5, 0xca, 0xeb, 0x38, 0x67, 0x1c, 0xfc, 0xfa, 0xcf, 0xf5, 0xff, 0x91, 0x6b,
	0x42, 0x4e, 0x31, 0xd7, 0xef, 0xcf, 0x59, 0x34, 0x2d, 0x85, 0x3c, 0x3e, 0x58, 0x55, 0xf2, 0x13,
	0x7d, 0x5b, 0x3d, 0x69, 0x3c, 0x3f, 0x9a, 0x72, 0x35, 0x4b, 0x27, 0xc3, 0x40, 0x2c, 0x46, 0xa5,
	0x1f, 0xfe, 0x5a, 0x4f, 0xc5, 0x28, 0x3e, 0x9d, 0x8e, 0x8a, 0x5f, 0xed, 0xcf, 0x64, 0x1c, 0x4c,
	0x3a, 0x78, 0xc9, 0x7d, 0xf8, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xb9, 0x5e, 0xe0, 0x81,
	0x0f, 0x00, 0x00,
}
