// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mojo/rpc/message.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" gorm:"-" xml:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" gorm:"-" xml:"-" bson:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_995f18ecc606040e, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "mojo.rpc.Message")
}

func init() { proto.RegisterFile("mojo/rpc/message.proto", fileDescriptor_995f18ecc606040e) }

var fileDescriptor_995f18ecc606040e = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0xcd, 0xcf, 0xca,
	0xd7, 0x2f, 0x2a, 0x48, 0xd6, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x89, 0xeb, 0x15, 0x15, 0x24, 0x2b, 0x71, 0x72, 0xb1, 0xfb, 0x42,
	0xa4, 0x9c, 0xa2, 0x66, 0x3c, 0x96, 0x63, 0xe0, 0x12, 0xcb, 0x2f, 0x4a, 0xd7, 0x03, 0x49, 0xeb,
	0xe6, 0x24, 0xe6, 0x41, 0x58, 0x20, 0x85, 0x4e, 0x3c, 0x50, 0x65, 0x01, 0x20, 0x03, 0x02, 0x18,
	0xa3, 0x74, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0xe1, 0xca, 0xc1,
	0x56, 0xa5, 0xe7, 0xeb, 0x17, 0x64, 0xa7, 0xeb, 0xc3, 0xac, 0xb6, 0x2e, 0x2a, 0x48, 0x4e, 0x62,
	0x03, 0xdb, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x27, 0x14, 0x99, 0xc2, 0x91, 0x00, 0x00,
	0x00,
}
